/**
 * Microstock Platform Configurations, Authentic Brand Logos, and Validation Rules
 */

export const PLATFORMS = {
  general: {
    id: 'general',
    name: 'General',
    logoSvg: `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#818cf8" stroke-width="2.5"><circle cx="12" cy="12" r="8.5"/></svg>`,
    color: '#818cf8',
    colorBg: 'rgba(99, 102, 241, 0.16)',
    colorBorder: 'rgba(99, 102, 241, 0.35)',
    titleMaxLen: 200,
    titleMinLen: 5,
    keywordMin: 5,
    keywordMax: 50,
    keywordRecommended: 30,
    categoriesRequired: 0,
    csvColumns: ['Filename', 'Title', 'Description', 'Keywords', 'Category'],
    categories: ['General', 'Abstract', 'Animals', 'Architecture', 'Business', 'Food', 'Nature', 'People', 'Technology'],
    description: 'Universal microstock metadata format compatible with all major stock agencies.'
  },
  adobe: {
    id: 'adobe',
    name: 'AdobeStock',
    logoSvg: `<span style="color:#e056fd;font-weight:900;font-size:13px;letter-spacing:-0.05em;line-height:1">St</span>`,
    color: '#e056fd',
    colorBg: 'rgba(224, 86, 253, 0.16)',
    colorBorder: 'rgba(224, 86, 253, 0.35)',
    titleMaxLen: 200,
    titleMinLen: 5,
    keywordMin: 5,
    keywordMax: 50,
    keywordRecommended: 30,
    categoriesRequired: 1,
    csvColumns: ['Filename', 'Title', 'Keywords', 'Category'],
    categories: [
      'Animals', 'Buildings and Architecture', 'Business', 'Drinks', 'Environment',
      'States of Mind', 'Food', 'Graphic Resources', 'Hobbies and Leisure', 'Industry',
      'Landscapes', 'Lifestyle', 'People', 'Plants and Flowers', 'Culture and Religion',
      'Science', 'Social Issues', 'Sports', 'Technology', 'Transport', 'Travel'
    ],
    description: 'Title required (max 200 chars), up to 50 keywords ordered by relevance, 1 category.'
  },
  magnific: {
    id: 'magnific',
    name: 'Magnific',
    logoSvg: `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#facc15" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M3 18l1.5-10 4.5 4.5L12 6l3 6.5 4.5-4.5L21 18H3z"/></svg>`,
    color: '#facc15',
    colorBg: 'rgba(250, 204, 21, 0.16)',
    colorBorder: 'rgba(250, 204, 21, 0.35)',
    titleMaxLen: 250,
    titleMinLen: 5,
    keywordMin: 5,
    keywordMax: 50,
    keywordRecommended: 30,
    categoriesRequired: 0,
    csvColumns: ['Filename', 'Title', 'Prompt', 'Keywords'],
    categories: ['AI Art', 'Generative', 'Concept Art', '3D Render', 'Photography', 'Illustration'],
    description: 'AI Upscaler & Image Generation prompt and metadata cataloger.'
  },
  shutterstock: {
    id: 'shutterstock',
    name: 'Shutterstock',
    logoSvg: `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#38bdf8" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z"/><circle cx="12" cy="13" r="2.5"/></svg>`,
    color: '#38bdf8',
    colorBg: 'rgba(56, 189, 248, 0.16)',
    colorBorder: 'rgba(56, 189, 248, 0.35)',
    titleMaxLen: 200,
    titleMinLen: 5,
    keywordMin: 7,
    keywordMax: 50,
    keywordRecommended: 45,
    categoriesRequired: 1,
    csvColumns: ['Filename', 'Description', 'Keywords', 'Categories'],
    categories: [
      'Abstract', 'Animals/Wildlife', 'Arts', 'Backgrounds/Textures', 'Beauty/Fashion',
      'Buildings/Landmarks', 'Business/Finance', 'Celebrities', 'Education', 'Food and drink',
      'Healthcare/Medical', 'Holidays', 'Industrial', 'Interiors', 'Miscellaneous',
      'Nature', 'Objects', 'Parks/Outdoor', 'People', 'Religion', 'Science',
      'Signs/Symbols', 'Sports/Recreation', 'Technology', 'Transportation', 'Vintage'
    ],
    videoCategories: [
      'Animals/Wildlife', 'Arts', 'Backgrounds/Textures', 'Buildings/Landmarks',
      'Business/Finance', 'Education', 'Food and drink', 'Healthcare/Medical',
      'Holidays', 'Industrial', 'Nature', 'Objects', 'People', 'Religion',
      'Science', 'Signs/Symbols', 'Sports/Recreation', 'Technology', 'Transportation'
    ],
    description: 'Unique Description in English (max 200 chars), up to 50 keywords, 1 or 2 official Categories.'
  },
  vecteezy: {
    id: 'vecteezy',
    name: 'Vecteezy',
    logoSvg: `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#f97316" stroke-width="2.5"><rect x="12" y="2" width="13" height="13" rx="1.5" transform="rotate(45 12 2)"/></svg>`,
    color: '#f97316',
    colorBg: 'rgba(255, 107, 0, 0.16)',
    colorBorder: 'rgba(255, 107, 0, 0.35)',
    titleMaxLen: 100,
    titleMinLen: 5,
    keywordMin: 5,
    keywordMax: 50,
    keywordRecommended: 30,
    categoriesRequired: 1,
    csvColumns: ['Filename', 'Title', 'Keywords', 'License'],
    categories: ['Vectors', 'Icons', 'Illustrations', 'Patterns', 'Backgrounds', 'Templates'],
    description: 'Optimized for Vector and Graphic asset metadata submission.'
  },
  depositphotos: {
    id: 'depositphotos',
    name: 'Depositphotos',
    logoSvg: `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#3b82f6" stroke-width="2.5"><rect x="12" y="2" width="13" height="13" rx="1.5" transform="rotate(45 12 2)"/></svg>`,
    color: '#3b82f6',
    colorBg: 'rgba(59, 130, 246, 0.16)',
    colorBorder: 'rgba(59, 130, 246, 0.35)',
    titleMaxLen: 150,
    titleMinLen: 5,
    keywordMin: 5,
    keywordMax: 50,
    keywordRecommended: 30,
    categoriesRequired: 1,
    csvColumns: ['Filename', 'Title', 'Description', 'Keywords', 'Categories'],
    categories: [
      'Abstract', 'Animals', 'Architecture', 'Business', 'Cities', 'Education',
      'Food & Drink', 'Holidays', 'Industry', 'Nature', 'People', 'Science', 'Shopping',
      'Sports', 'Technology', 'Transportation', 'Backgrounds'
    ],
    description: 'Title, Description, 50 keywords, and primary category tag.'
  },
  rf123: {
    id: 'rf123',
    name: '123RF',
    logoSvg: `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#c084fc" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4"/></svg>`,
    color: '#c084fc',
    colorBg: 'rgba(192, 132, 252, 0.16)',
    colorBorder: 'rgba(192, 132, 252, 0.35)',
    titleMaxLen: 150,
    titleMinLen: 5,
    keywordMin: 5,
    keywordMax: 50,
    keywordRecommended: 30,
    categoriesRequired: 0,
    csvColumns: ['Filename', 'Title', 'Description', 'Keywords'],
    categories: [],
    description: 'Title, Description, and comma-separated keywords.'
  },
  dreamstime: {
    id: 'dreamstime',
    name: 'Dreamstime',
    logoSvg: `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#22c55e" stroke-width="2.5"><circle cx="12" cy="12" r="8.5"/></svg>`,
    color: '#22c55e',
    colorBg: 'rgba(34, 197, 94, 0.16)',
    colorBorder: 'rgba(34, 197, 94, 0.35)',
    titleMaxLen: 200,
    titleMinLen: 5,
    keywordMin: 5,
    keywordMax: 80,
    keywordRecommended: 40,
    categoriesRequired: 1,
    csvColumns: ['Filename', 'Image Name', 'Description', 'Keywords', 'Category'],
    categories: [
      'Abstract', 'Animal', 'Arts & Architecture', 'Business', 'Editorial',
      'Illustrations & Clipart', 'IT & C', 'Nature', 'Object', 'People', 'Travel'
    ],
    description: 'Image Name (Title), Description, up to 80 keywords, and Primary Category.'
  },
  freepik: {
    id: 'freepik',
    name: 'Freepik',
    logoSvg: `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#2563eb" stroke-width="2.5"><path stroke-linecap="round" stroke-linejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>`,
    color: '#2563eb',
    colorBg: 'rgba(37, 99, 235, 0.16)',
    colorBorder: 'rgba(37, 99, 235, 0.35)',
    titleMaxLen: 100,
    titleMinLen: 5,
    keywordMin: 5,
    keywordMax: 50,
    keywordRecommended: 30,
    categoriesRequired: 0,
    csvColumns: ['Filename', 'Title', 'Keywords'],
    categories: ['Vectors', 'Photos', 'PSD', 'Icons'],
    description: 'Title and Keywords optimized for Freepik contributor uploads.'
  },
  istock: {
    id: 'istock',
    name: 'iStock',
    logoSvg: `<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#00dbe9" stroke-width="2.5"><rect x="3" y="3" width="18" height="18" rx="2"/></svg>`,
    color: '#00dbe9',
    colorBg: 'rgba(0, 219, 233, 0.16)',
    colorBorder: 'rgba(0, 219, 233, 0.35)',
    titleMaxLen: 200,
    titleMinLen: 5,
    keywordMin: 5,
    keywordMax: 50,
    keywordRecommended: 30,
    categoriesRequired: 0,
    csvColumns: ['Filename', 'Title', 'Description', 'Keywords'],
    categories: [],
    description: 'Title, Description, and Keywords for iStock / Getty Images.'
  }
};
